### ISSUE TITLE
Deadlock 

### ISSUE THREAD

**Issue by tobiaswjohn** [kas-lab/suave#150]
![Screenshot from 2024-02-19 16-06-07](https://github.com/kas-lab/suave/assets/34936267/a95b3487-4e25-4964-a95a-98214e72c1c1)

**Comment by Rezenders** [comment]
```
[suave_reasoner-12] [INFO] [1708356000.317061707] [suave_reasoner]: Exited metacontrol_loop_callback
[time_constrained_mission-2] [INFO] [1708356000.472008145] [mission_node]: Starting search_pipeline task
[suave_reasoner-12] [INFO] [1708356000.486885332] [suave_reasoner]: Objective Action Callback!
[suave_reasoner-12] [INFO] [1708356000.491769117] [suave_reasoner]: Creating Objective tomasys.obj_f_maintain_motion_170835600
[suave_reasoner-12] [INFO] [1708356000.493956174] [suave_reasoner]: grounded_configuration initialized to: None
[suave_reasoner-12] [INFO] [1708356000.509208522] [suave_reasoner]: Objective Action Callback!
[suave_reasoner-12] [INFO] [1708356000.512230699] [suave_reasoner]: Creating Objective tomasys.obj_f_maintain_motion_170835600
[suave_reasoner-12] [INFO] [1708356000.513107096] [suave_reasoner]: grounded_configuration initialized to: None
[task_bridge_metacontrol-14] [INFO] [1708356000.524593207] [adpatation_goal_bridge]: Waiting for future to complete
[task_bridge_metacontrol-14] [INFO] [1708356000.530874373] [adpatation_goal_bridge]: Sending adaptation goal  f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356000.533434587] [adpatation_goal_bridge]: MROS objective f_maintain_motion sent!!!
[suave_reasoner-12] [INFO] [1708356000.541201930] [suave_reasoner]: Objective Action Callback!
[task_bridge_metacontrol-14] [INFO] [1708356000.545046102] [adpatation_goal_bridge]: Waiting for future to complete
[suave_reasoner-12] [INFO] [1708356000.545049479] [suave_reasoner]: Creating Objective tomasys.obj_f_generate_search_path_170835600
[suave_reasoner-12] [INFO] [1708356000.545849914] [suave_reasoner]: grounded_configuration initialized to: None
[suave_reasoner-12] [INFO] [1708356000.546619382] [suave_reasoner]: Objective Action Callback!
[task_bridge_metacontrol-14] [INFO] [1708356000.548927905] [adpatation_goal_bridge]: Sending adaptation goal  f_maintain_motion
[suave_reasoner-12] [INFO] [1708356000.550453025] [suave_reasoner]: Creating Objective tomasys.obj_f_maintain_motion_170835600
[suave_reasoner-12] [INFO] [1708356000.551191324] [suave_reasoner]: grounded_configuration initialized to: None
[task_bridge_metacontrol-14] [INFO] [1708356000.552364206] [adpatation_goal_bridge]: MROS objective f_maintain_motion sent!!!
[task_bridge_metacontrol-14] [INFO] [1708356000.555242934] [adpatation_goal_bridge]: >> Feedback received:
[task_bridge_metacontrol-14] [INFO] [1708356000.556277988] [adpatation_goal_bridge]:     Solving: obj_f_maintain_motion_170835600 of type f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356000.556927602] [adpatation_goal_bridge]:     Objective status: UNGROUNDED
[suave_reasoner-12] [INFO] [1708356000.557420704] [suave_reasoner]: Objective Action Callback!
[task_bridge_metacontrol-14] [INFO] [1708356000.557571245] [adpatation_goal_bridge]:     QAs Status: 
[task_bridge_metacontrol-14] [INFO] [1708356000.558197165] [adpatation_goal_bridge]:     Current Function Grounding: 
[suave_reasoner-12] [INFO] [1708356000.564289608] [suave_reasoner]: Objective Action Callback!
[task_bridge_metacontrol-14] [INFO] [1708356000.565433605] [adpatation_goal_bridge]: Waiting for future to complete
[suave_reasoner-12] [INFO] [1708356000.567323246] [suave_reasoner]: Creating Objective tomasys.obj_f_generate_search_path_170835600
[suave_reasoner-12] [INFO] [1708356000.568074119] [suave_reasoner]: grounded_configuration initialized to: None
[task_bridge_metacontrol-14] [INFO] [1708356000.569011270] [adpatation_goal_bridge]: Sending adaptation goal  f_generate_search_path
[suave_reasoner-12] [INFO] [1708356000.575525111] [suave_reasoner]: Objective Action Callback!
[suave_reasoner-12] [INFO] [1708356000.575897607] [suave_reasoner]: Creating Objective tomasys.obj_f_maintain_motion_170835600
[suave_reasoner-12] [INFO] [1708356000.576574341] [suave_reasoner]: grounded_configuration initialized to: None
[time_constrained_mission-2] [INFO] [1708356000.577109170] [mission_node]: Task search_pipeline completed
[suave_reasoner-12] [INFO] [1708356000.579018688] [suave_reasoner]: Creating Objective tomasys.obj_f_generate_search_path_170835600
[suave_reasoner-12] [INFO] [1708356000.579984312] [suave_reasoner]: grounded_configuration initialized to: None
[task_bridge_metacontrol-14] [INFO] [1708356000.581512017] [adpatation_goal_bridge]: MROS objective f_generate_search_path sent!!!
[task_bridge_metacontrol-14] [INFO] [1708356000.583013292] [adpatation_goal_bridge]: Waiting for future to complete
[suave_reasoner-12] [INFO] [1708356000.585657643] [suave_reasoner]: Cancel action callback!
[suave_reasoner-12] [WARN] [1708356000.586892209] [suave_reasoner]: New Configuration for function_name f_maintain_motion requested: fd_unground
[task_bridge_metacontrol-14] [INFO] [1708356000.588284771] [adpatation_goal_bridge]: Sending adaptation goal  f_generate_search_path
[task_bridge_metacontrol-14] [INFO] [1708356000.590233592] [adpatation_goal_bridge]: MROS objective f_generate_search_path sent!!!
[task_bridge_metacontrol-14] [INFO] [1708356000.619305041] [adpatation_goal_bridge]: >> Feedback received:
[task_bridge_metacontrol-14] [INFO] [1708356000.620771501] [adpatation_goal_bridge]:     Solving: obj_f_maintain_motion_170835600 of type f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356000.621690638] [adpatation_goal_bridge]:     Objective status: UNGROUNDED
[task_bridge_metacontrol-14] [INFO] [1708356000.622521791] [adpatation_goal_bridge]:     QAs Status: 
[task_bridge_metacontrol-14] [INFO] [1708356000.623319932] [adpatation_goal_bridge]:     Current Function Grounding: 
[task_bridge_metacontrol-14] [INFO] [1708356000.627308014] [adpatation_goal_bridge]: >> Feedback received:
[task_bridge_metacontrol-14] [INFO] [1708356000.628255004] [adpatation_goal_bridge]:     Solving: obj_f_generate_search_path_170835600 of type f_generate_search_path
[task_bridge_metacontrol-14] [INFO] [1708356000.628932920] [adpatation_goal_bridge]:     Objective status: UNGROUNDED
[task_bridge_metacontrol-14] [INFO] [1708356000.629560182] [adpatation_goal_bridge]:     QAs Status: 
[task_bridge_metacontrol-14] [INFO] [1708356000.630162538] [adpatation_goal_bridge]:     Current Function Grounding: 
[mode_manager-11] [INFO] [1708356000.631343123] [__mode_manager]: -> callback change_mode of f_maintain_motion to fd_unground
[mode_manager-11] [INFO] [1708356000.631409798] [__mode_manager]:  changing mode of f_maintain_motion to fd_unground
[mode_manager-11] [INFO] [1708356000.631911335] [__mode_manager]:  changing state of f_maintain_motion_node: deactivate
[recover_thrusters-10] [WARN] [1708356000.633008745] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
[mros2_system_modes_bridge-13] [INFO] [1708356000.634954962] [system_modes_bridge]: requested node name is f_maintain_motion and mode is fd_unground
[recover_thrusters-10] [WARN] [1708356000.639793282] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
[mode_manager-11] [INFO] [1708356000.679465998] [__mode_manager]: -> callback change_mode of f_maintain_motion to fd_unground
[mode_manager-11] [INFO] [1708356000.679540688] [__mode_manager]:  changing mode of f_maintain_motion to fd_unground
[mode_manager-11] [INFO] [1708356000.680022628] [__mode_manager]:  changing state of f_maintain_motion_node: deactivate
[recover_thrusters-10] [WARN] [1708356000.689089199] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
[mros2_system_modes_bridge-13] [INFO] [1708356000.691343761] [system_modes_bridge]: Response received: True
[suave_reasoner-12] Traceback (most recent call last):
[suave_reasoner-12]   File "/home/gus/exp_metacontrol_ws/install/suave_metacontrol/lib/suave_metacontrol/suave_reasoner", line 33, in <module>
[suave_reasoner-12]     sys.exit(load_entry_point('suave-metacontrol', 'console_scripts', 'suave_reasoner')())
[suave_reasoner-12]   File "/home/gus/exp_metacontrol_ws/build/suave_metacontrol/suave_metacontrol/suave_reasoner.py", line 58, in main
[suave_reasoner-12]     rclpy.spin(pipeline_inspection_reasoner, executor=mt_executor)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[suave_reasoner-12]     executor.spin_once()
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 794, in spin_once
[suave_reasoner-12]     self._spin_once_impl(timeout_sec)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 791, in _spin_once_impl
[suave_reasoner-12]     future.result()
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
[suave_reasoner-12]     raise self.exception()
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[suave_reasoner-12]     self._handler.send(None)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
[suave_reasoner-12]     await call_coroutine(entity, arg)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 403, in _execute_waitable
[suave_reasoner-12]     await waitable.execute(data)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/action/server.py", line 478, in execute
[suave_reasoner-12]     await self._execute_cancel_request(taken_data['cancel'])
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/action/server.py", line 365, in _execute_cancel_request
[suave_reasoner-12]     response = await await_or_execute(self._cancel_callback, goal_handle)
[suave_reasoner-12]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[suave_reasoner-12]     return callback(*args)
[suave_reasoner-12]   File "/home/gus/exp_metacontrol_ws/build/mros2_reasoner/mros2_reasoner/ros_reasoner.py", line 122, in objective_cancel_goal_callback
[suave_reasoner-12]     if self.remove_objective(
[suave_reasoner-12]   File "/home/gus/exp_metacontrol_ws/build/mros2_reasoner/mros2_reasoner/reasoner.py", line 58, in remove_objective
[suave_reasoner-12]     destroy_entity(old_fg_instance)
[suave_reasoner-12]   File "/home/gus/.local/lib/python3.10/site-packages/owlready2/prop.py", line 997, in destroy_entity
[suave_reasoner-12]     e.namespace.world.graph.destroy_entity(e.storid, destroyer, relation_updater, undoer_objs, undoer_datas)
[suave_reasoner-12] AttributeError: 'NoneType' object has no attribute 'namespace'
[task_bridge_metacontrol-14] [INFO] [1708356001.133613487] [adpatation_goal_bridge]: cancel f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356001.134622793] [adpatation_goal_bridge]: cancel requested f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356003.220832346] [adpatation_goal_bridge]: cancel f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1708356003.221869864] [adpatation_goal_bridge]: cancel requested f_maintain_motion
[mros2_system_modes_bridge-13] [INFO] [1708356005.463177450] [system_modes_bridge]: requested node name is f_maintain_motion and mode is fd_all_thrusters
[mode_manager-11] [INFO] [1708356005.473455533] [__mode_manager]: -> callback change_mode of f_maintain_motion to fd_all_thrusters
[mode_manager-11] [INFO] [1708356005.473540572] [__mode_manager]:  changing mode of f_maintain_motion to fd_all_thrusters
[mode_manager-11] [INFO] [1708356005.473886980] [__mode_manager]:  changing state of f_maintain_motion_node: deactivate
[recover_thrusters-10] [WARN] [1708356005.475035405] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
[recover_thrusters-10] [WARN] [1708356005.477154305] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
[mode_manager-11] [INFO] [1708356005.477415032] [__mode_manager]: -> callback change_mode of f_maintain_motion to fd_all_thrusters
[mode_manager-11] [INFO] [1708356005.477577155] [__mode_manager]:  changing mode of f_maintain_motion to fd_all_thrusters
[mode_manager-11] [INFO] [1708356005.478083020] [__mode_manager]:  changing state of f_maintain_motion_node: deactivate
[recover_thrusters-10] [WARN] [1708356005.479066247] [rcl_lifecycle]: No transition matching deactivate found for current state inactive
```

**Comment by Rezenders** [comment]
Solved at [0288071](https://github.com/kas-lab/suave/commit/02880713975970e3d2881f9b756eaa874d077b7d)

**Comment by Rezenders** [comment]
Not solved, it is still happening in some machines

**Comment by Rezenders** [comment]
I thought about setting the objective action and the metacontrol timer to have different callback groups, but when this is set an objective can be canceled and then the metacontrol can set it to activated. So they have to be in the same mutually exclusive callback group

**Comment by Rezenders** [comment]
```
[time_constrained_mission-2] [INFO] [1710423942.147647895] [mission_node]: Starting inspect_pipeline task
[task_bridge_metacontrol-14] [INFO] [1710423942.151723053] [adpatation_goal_bridge]: Sending adaptation goal  f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1710423942.152837480] [adpatation_goal_bridge]: MROS objective f_maintain_motion sent!!!
[task_bridge_metacontrol-14] [INFO] [1710423942.153219773] [adpatation_goal_bridge]: Waiting for mros_objective future to complete
[task_bridge_metacontrol-14] [INFO] [1710423942.162155118] [adpatation_goal_bridge]: Future send mros_objective completed f_maintain_motion
[suave_reasoner-12] [INFO] [1710423942.162374071] [suave_reasoner]: Objective Action Callback!
[task_bridge_metacontrol-14] [INFO] [1710423942.163054233] [adpatation_goal_bridge]: Sending adaptation goal  f_follow_pipeline
[task_bridge_metacontrol-14] [INFO] [1710423942.163653058] [adpatation_goal_bridge]: MROS objective f_follow_pipeline sent!!!
[task_bridge_metacontrol-14] [INFO] [1710423942.164156483] [adpatation_goal_bridge]: Waiting for mros_objective future to complete
[suave_reasoner-12] [INFO] [1710423942.167660927] [suave_reasoner]: Creating Objective tomasys.obj_f_maintain_motion_171042394
[task_bridge_metacontrol-14] [INFO] [1710423942.168915961] [adpatation_goal_bridge]: Future send mros_objective completed f_follow_pipeline
[suave_reasoner-12] [INFO] [1710423942.169499736] [suave_reasoner]: Objective Action Callback!
[suave_reasoner-12] [INFO] [1710423942.170435713] [suave_reasoner]: grounded_configuration initialized to: None
[suave_reasoner-12] [INFO] [1710423942.173062842] [suave_reasoner]: Creating Objective tomasys.obj_f_follow_pipeline_171042394
[suave_reasoner-12] [INFO] [1710423942.173812883] [suave_reasoner]: Objective tomasys.obj_f_maintain_motion_171042394 created!
[suave_reasoner-12] [INFO] [1710423942.174100250] [suave_reasoner]: grounded_configuration initialized to: None
[suave_reasoner-12] [INFO] [1710423942.175149637] [suave_reasoner]: Objective tomasys.obj_f_follow_pipeline_171042394 created!
[task_bridge_metacontrol-14] [INFO] [1710423942.175381360] [adpatation_goal_bridge]: >> Feedback received:
[task_bridge_metacontrol-14] [INFO] [1710423942.175821996] [adpatation_goal_bridge]:     Solving: obj_f_maintain_motion_171042394 of type f_maintain_motion
[task_bridge_metacontrol-14] [INFO] [1710423942.176399264] [adpatation_goal_bridge]:     Objective status: UNGROUNDED
[task_bridge_metacontrol-14] [INFO] [1710423942.176814544] [adpatation_goal_bridge]:     QAs Status: 
[task_bridge_metacontrol-14] [INFO] [1710423942.177200303] [adpatation_goal_bridge]:     Current Function Grounding: 
[task_bridge_metacontrol-14] [INFO] [1710423942.178342987] [adpatation_goal_bridge]: >> Feedback received:
[task_bridge_metacontrol-14] [INFO] [1710423942.178778761] [adpatation_goal_bridge]:     Solving: obj_f_follow_pipeline_171042394 of type f_follow_pipeline
[task_bridge_metacontrol-14] [INFO] [1710423942.179179999] [adpatation_goal_bridge]:     Objective status: UNGROUNDED
[task_bridge_metacontrol-14] [INFO] [1710423942.179791586] [adpatation_goal_bridge]:     QAs Status: 
[task_bridge_metacontrol-14] [INFO] [1710423942.180206214] [adpatation_goal_bridge]:     Current Function Grounding: 

```
